### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by Laurel-rao** [lanyulei/ferry_web#67]
- it seems that python error.
- here is log of error.
```
Building: D:\environment\nodejs\node.exe D:\mypro\angular\test-app\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags=
--libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'D:\\environment\\nodejs\\node.exe',
gyp verb cli   'D:\\mypro\\angular\\test-app\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.15.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\mypro\angular\test-app\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\mypro\angular\test-app\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\mypro\angular\test-app\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\mypro\angular\test-app\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\mypro\angular\test-app\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\mypro\angular\test-app\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\mypro\angular\test-app\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\mypro\angular\test-app\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\mypro\angular\test-app\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\mypro\angular\test-app\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\mypro\angular\test-app\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\mypro\angular\test-app\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python D:\environment\python3.6\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: D:\environment\python3.6\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "D:\\environment\\nodejs\\node.exe" "D:\\mypro\\angular\\test-app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass
_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\mypro\angular\test-app\node_modules\node-sass
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.9.3 (node_modules\node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.9.3 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

up to date in 68.168s

30 packages are looking for funding
  run `npm fund` for details

```

**Comment by Laurel-rao** [comment]
my fault
